api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    dapr:
      appId: invoicing-api
      appPort: 8080
      enabled: {{ .Env.ENABLE_DAPR }}
    ingress:
      external: false
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--appinsights
        value: {{ .Env.APPINSIGHTS_CONNECTIONSTRING }}
      - name: connectionstrings--storage
        value: {{ .Env.STORAGE_CONNECTIONSTRING }}
      - name: identity--clientcredentials--clientid
        value: {{ .Env.INVOICING_API_IDENTITY_CLIENTCREDENTIALS_CLIENTID }}
      - name: identity--clientcredentials--clientsecret
        value: {{ .Env.INVOICING_API_IDENTITY_CLIENTCREDENTIALS_CLIENTSECRET }}
  template:
    containers:
      - image: {{ .Image }}
        name: invoicing-api
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: Identity__ClientCredentials__ClientId
            secretRef: identity--clientcredentials--clientid
          - name: Identity__ClientCredentials__ClientSecret
            secretRef: identity--clientcredentials--clientsecret
          - name: Identity__Url
            value: https://identity-api.{{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_DEFAULT_DOMAIN }}
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: ConnectionStrings__appinsights
            secretRef: connectionstrings--appinsights
          - name: AzureBlobStorageConnectionString
            secretRef: connectionstrings--storage
    scale:
      minReplicas: 1
tags:
  azd-service-name: invoicing-api
  aspire-resource-name: invoicing-api