name: eShop Pull Request Validation - .NET MAUI

on:
  pull_request:
    branches:
      - '**'
    paths:
      - 'src/eShop.ClientApp/**'
      - 'tests/eShop.ClientApp.UnitTests/**'
      - '.github/workflows/pr-validation-maui.yml'
  push:
    branches:
      - main
      - dev
    paths:
      - 'src/eShop.ClientApp/**'
      - 'tests/eShop.ClientApp.UnitTests/**'
      - '.github/workflows/pr-validation-maui.yml'

jobs:  
  test:
    runs-on: windows-latest    
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET (global.json)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
      - name: Update Workloads
        run: dotnet workload update

      - name: Install Workloads
        shell: pwsh
        run: |
          dotnet workload install android
          dotnet workload install ios
          dotnet workload install maccatalyst
          dotnet workload install maui

      - name: Build 
        run: dotnet build src/eShop.ClientApp/eShop.ClientApp.csproj
        
      - name: Test
        run: dotnet test tests/eShop.ClientApp.UnitTests/eShop.ClientApp.UnitTests.csproj
